### ISSUE TITLE
Feedback wanted: fsharp.org redesign

### ISSUE THREAD

**Issue by FSSF** [fsharp/fsfoundation#680] opened 2017-08-23 22:24 UTC
The F# Software Foundation Board of Trustees has begun the process of working on a complete redesign and reworking of fsharp.org.

The plan is to hire a design firm to bring a professional polish to fsharp.org, with a specific focus on the user experience and usability. They will be focusing on helping us improve the user experience for people coming to fsharp.org. This will be coupled with some custom development to fix some technical annoyances about the current site.

We have some initial technical and design requirements that we will be taking into account. I'd like to list off our main objectives:

On the technical side:

- Unify fsharp.org workflow and subdomains (eliminate or streamline foundation.fsharp.org, and bring membership status and sign-ups into main site)
- Make it easier for the community to contribute content (ideally in GitHub, via markdown)
- Feature F# code on fsharp.org, and provide a tryfsharp-like mechanism for execution in browser

The bulk of this effort will actually be on the design and user experience side:

- Identify main objectives a user coming to fsharp.org would want to experience
- Improve site navigation and organization to allow it to be easier to discover important information
- Identify requirements for new, updated, or streamlined content, as well as content that can be deemphasized or removed
- Help new users of fsharp.org find what they need, quickly

With that in mind, we would like your help!

Please provide feedback of what you think is important. In particular, we'd love to hear feedback on the following topics:

1. What specific audiences should fsharp.org target?
2. For each audience, what should be the main goals when a user first visits fsharp.org?
3. What major scenarios do we need to support for fsharp.org?

Also feel free to provide feedback on your main annoyances with the current site, or any other issues that may be relevant. Note that we are _not_ looking for UI suggestions at this point ("look and feel"), and more after honing in on the best strategy/goals/objectives.

For each major idea, please open a [**new issue**](https://github.com/fsharp/fsfoundation/issues/new) (so each idea can have its own discussion), and link to it here in a comment. Vote on comments within this issue which you feel are important or not important. This will allow our design firm to easily watch this issue and incorporate feedback from everybody as smoothly as possible, as well as to see what people find good or lacking in the current fsharp.org experience.

Thank you,
Reed Copsey, Jr.
Executive Director - F# Software Foundation
On behalf of the Board of Trustees

**Comment by FSSF** [comment] 2017-08-23 22:25
[Have a single http://fsharp.org/use that detects platform - via @dsyme](https://github.com/fsharp/fsfoundation/issues/681)

**Comment by FSSF** [comment] 2017-08-23 22:30
Request: [The fsharp.org website should show some code](https://github.com/fsharp/fsfoundation/issues/682) - via @julienXX

**Comment by FSSF** [comment] 2017-08-23 22:33
Idea: [Taking an opinionated approach to getting started with F#](https://github.com/fsharp/fsfoundation/issues/683) via @cartermp

**Comment by sergey-tihon** [comment] 2017-08-25 08:13
I want to be able to execute F# code on `fsharp.org` and see the result.
Something similar to [http://www.tryfsharp.org](http://www.tryfsharp.org) would be awesome or at least integration with Fable REPL and couple interactive F# tutorials of beginners.

**Comment by cartermp** [comment] 2017-08-25 15:58
Here's what I think are the most important things for the front page, from the perspective of getting new people interested, in stack-rank order:

1. Code sample showing F# doing something simple, but with "sexy" syntax.  People need to see F# code and think, "gosh, that looks nice and I want to use this".  Runnable is a huge plus, but I certainly wouldn't put a hold on publishing a new version of the site without this.
2. Either a big UI element (button?) that takes you to a Get Started page, or have that content on the front page.  This content should show different ways to use F# _but recommend a single way_.  This way should be portable and as low-friction as possible.  Links at the bottom of this to documentation for learning F# (official docs, F# wiki, and F# for Fun and Profit gitbook).
3. Big link or section dedicated to the F# community and FSSF.  This would show slack, community resources, open source projects, and how to get involved with the FSSF.
4. The front page must load and be usable on a slow internet connection.
5. Accessibility - there should be links below to view the site in other supported languages.

Unfortunately, I'm absolutely awful at design, so I can't offer up any reasonable opinions about that.  I tend to prefer as little clutter as possible, but that's just my personal taste.

**Comment by jackfoxy** [comment] 2017-08-25 16:41
I'm going to be iconoclastic.

The F# org site should first and foremost be useful for experienced F# people. The site should emphasize targeting long-term users first. I don't mean to denigrate outreach, there is still room for that on the site. I think useful for the established community and outreach work together.

I don't have specific recommendations right now (and I will be offline for about 10 days).

**Comment by mathias-brandewinder** [comment] 2017-08-25 20:50
@jackfoxy I am not sure I understand your reasoning. In my view, F# veterans know where to find resources already, and do not need fsharp.org to find help or information. By contrast, newcomers encounter simple issues, and fsharp.org is likely going to be one of the first websites they will encounter, so to me it seems important to make that a single place where they can find all the commonly asked information, and will make their first hours into F# easy and pleasant, like, "how do I install F# so that I can try it out now", or "what are good learning resources". It seems to me that outreach to newcomers *is* a priority, if we want adoption to grow.
What information for experienced F#ers would you like to see on fsharp.org? Or, perhaps more pointedly, as an experienced F#er yourself, why would you go to the site?

**Comment by jackfoxy** [comment] 2017-08-25 23:58
That is the point. I don't go to the site. And I'm not saying we should not have all the amenities for newbies. 

As a "veteran" I still have to save off, or search for links of interest to me. I may not have time to keep up on the current Microsoft F# roadmap for 6 months at a time. Then if I suddenly take an interest my search comes up with all the past roadmaps, which could be scattered all over the place. 

Does everybody even know about the RFCs? Didn't there used to be an "engineering committee" loosely associated with the foundation?

OK, I don't have great suggestions, I just would like a reason to visit the site myself.

**Comment by Troxid** [comment] 2017-08-26 16:06
In my opinion, on main page `fsharp.org` should be step-by-step tutorial for instantly start work with fshap:
1. Installing fsharp compiler and build tool (done once)
2. (Optional) Installation cross-platform IDE (Atom, VCode, or Rider) and plugin (done once)
3. Creating first project (from terminal)
4. Adding some simple library (JSON or testing framework). Where can user find libraries? Reference to nuget.
5. Testing, building and run application (from terminal)
I know, may be it's easy and intuitive if did it in visual studio, but for manual settings need simple instruction.

Look at the good examples:
[.NET and C# - Get Started in 10 Minutes](https://www.microsoft.com/net/core#linuxubuntu)
[CREATE AN F# PROJECT IN VSCODE](https://codurance.com/2017/01/26/create-an-fsharp-project-in-vscode/)

Also, on main page should be written current version of F# compiler. It's not very important, but would be nice.

**Comment by MecuSorin** [comment] 2017-08-28 08:47
Before everything, it should be made in F# and a banner to be available for the github repo.

@cartermp I like the idea to have it translated in many languages, but from my perspective is the least important feature - will generate the most noise that will hinder development of more important features.

My 2 cents:
#### 1. Clear way to reach the Get Started section of the site with links to the the following sections:
1.1. Videos page: a page with 5 sections (list of links - thumbnails) : beginners, advanced, related(fable and other close related to F#) and meta (good video resources for FP, machine learning, etc.)
1.2. Experiment page - a try f# that works in all browsers (this is paramount)
1.3. Setup page - with sections for Win, IOS, Linux (with clear reproducible instructions, ideal setup with a list of plugins that can enhance the experience) and a container solution Vagrant or VirtualBox Linux image with everything setup
1.4. Tutorials page: page splitted in 2 sections: 
- first section 
1.4.1.1 beginner (create a project, language features, using paket and fake, a sample of imperative vs declarative, etc.)
1.4.1.2. advanced (anything that goes for a person that invested more than 5 hours in a FP language, some meta with emphasis on tools like testing, etc. )
- second section
1.4.2.1. web server (both flavors)
1.4.2.2. desktop client
1.4.2.3. js client
1.4.2.4. machine learning
### Important: A mechanism for the users to mark a tutorial that doesn't work
1.5. Links to documentation

#### 2. A clear picture of F# usage(where and **who** - some testimonials) and a road-map
#### 3. A news section (both F# and tooling) that will have a voting section for articles, blogs, tutorials, videos - grouped by month - hope that will gather resources for above 200 
#### 4. Section for community/foundation that beside what Carter suggested will have 2 sections:
4.1.1. request features (F# lang, tooling) with voting
4.1.2. easy tickets to grab (minimal context knowledge required)
4.1.3. important tickets to grab
### Important: if the veterans don't use this site, why bother?
4.2.1. Future events 
4.2.2. F# jobs adds from firms
4.2.3. Developers availability/requests for F# jobs.
4.2.4. A map with trainer/consultancy services (with an overall client experience voting system)
4.2.5. A pretext to see some charts made in F# (link to the 1.2. resource) that shows F# in the ecosystem (remuneration level, stackoverflow interest, etc.)
#### 5. An animated gif with max 10 lines of f# coding that is build, show tests output, show a nice graph (that is linking to the 1.2. sample)

# Don't hate me for the following suggestion but is a sign of sanity and maturity:
#### 6. What is bad in F# world with voting system - will help us grow based on real feedback. From my perspective this is a way to gain adopters, not lose them. If those "bad" topics are allowing comments maybe solutions will be provided for common problems (like a stackoverflow question), then we can mark them with tags as `solved`, `work around`, `to be fixed`, etc.

_I know I forgot something, but it eludes me in this moment, will come back later and edit._

**Comment by mathias-brandewinder** [comment] 2017-08-31 22:39
To piggyback on @MecuSorin comments: besides developers, I think we need to have a strong story for managers. A recurring question is **"Who uses F#? Do people use it in production?"**, and the [testimonials page](http://fsharp.org/testimonials/) is IMO very important in that regards.

That page is becoming a bit too large to navigate. Perhaps what would help would be:
* randomizing the display, so that different scenarios pop on top,
* using tags to filter, for instance `finance`, `games`...

**Comment by tpetricek** [comment] 2017-08-31 22:54
I think the scenarios are still very similar to those we had in mind when starting fsharp.org, but here is my updated list of what I think the page should cover (not necessarily sorted by importance).

1. **Technical decision makers (CTO level people)** - they come to the site when someone in their company wants to use F# or when they hear about it somewhere. Here is what we need to have:
   - High-level overview of why F# leads to more reliable software built faster
   - Experience reports/testimonials illustrating this, ideally from someone in their domain
   - Reassurance that they will be able to hire people, get training and consulting if needed

2. **Developers, analysts, etc. who are not F# users** - they come to the site after someone on the internet mentions they should look into F#. They need some more motivation to give it a try and solid getting started materials:
   - Some code snippet to show how awesome F# is for their domain (this can be quite a wide range, I'd say we need to cover: client web dev, server web dev, quant or data analyst, .net dev)
   - A way to play with F# easily for 10 minutes (Try F# like thingy or link to good interactive tutorials elsewhere)
   - A guide on how to get started - this can be further differentiated - something along the lines:  
     - Client-side developer should use .NET Core/Ionide/Fable (on any system)
     - Enterprise .NET developer should use VS proper on Windows
     - Server-side developer should use Ionide + Suave or VS proper + ASP.NET
     - Data analyst can be either Ionide or VS on Windows with FsLab 

3. **F# community members** - they come to fsharp.org for information about the foundation, user groups. I don't think they expect up-to-date news or tutorials on everything (there are better sources), but they need things like:
   - How to start a user group, materials they can use, etc.
   - Good materials for evangelising F# in their organisation and companies
   - Info about the activities provided by the foundation (mentoring, diversity, etc.)

**Comment by dsyme** [comment] 2017-08-31 22:55
Re “using tags to filter, for instance finance, games...”

I think this is one really important for decision makers – who aren’t looking for “social proof” but “business proof in my domain”

 

There are tags on all the existing testimonials which could be leveraged

 

Best

Don

**Comment by MecuSorin** [comment] 2017-08-31 23:10
My idea was to have teasers(with clear messages about the linked content)  that will take the user to the respective pages

**Comment by mathias-brandewinder** [comment] 2017-08-31 23:48
As it stands right now, the current [learning resources](http://fsharp.org/learn.html) page is messy, and will degrade over time, as more and more links/resources are added. The question "what are good learning resources?" for F# comes up often, so we should figure out a viable long-term solution.

At the very least, there should be a table of contents to navigate quickly to each type of resource, and find what you are looking for. If you don't pay attention, it's easy to miss that there is a big list of books half way down.

On one hand, it is not the role of the FSSF to decide what resources are good or bad, and (appear to) promote any of them; on the other hand, the raw lists are not very helpful in deciding what resource might be more or less appropriate for different audiences. Also, these lists will tend to grow over time, and some items will age and lose relevance - having a mechanism that will gracefully handle that would be helpful in keeping the site well maintained / curated.

As an example, the current order for the books random, as far as I can tell. I don't know what the right way to do this would be - here are some ideas, which may or may not be terrible:
* if the order is truly random, then it should be randomized, or (for instance) alphabetized,
* perhaps allowing some form of ranking based on user feedback would be a good idea? Or simply displaying things like Amazon ratings? 
* perhaps using tags (`compiler`, `beginner`, `web`...) might help sort through the list.
* perhaps adding age information would be a good idea, too.

**Comment by helgeu** [comment] 2017-09-01 07:31
Does there exist any statistics of the usage of the site? Is it possible to deduce anything highlevel of that statistics? Like whos visiting, why/what are they looking for, etc?

I like the angle of @tpetricek and the stats might help in pinpointing these targets for the site, and make sure some targets are not missed. I guess @tpetricek is more or less spot on with the largest audience, but the stats might be hidding some surprising facts ;-)

**Comment by lambdakris** [comment] 2017-09-05 04:41
Well, I think one area that could be taken into consideration with a site redesign is how to engage and mobilize F# users. This is a broad topic, but one way to think about it is through setting some imaginary goals about what effects or outcomes one might like to see. Here are some example goals that could be of value:

- Increase participation in RFCs
- Increase visibility of release notes/announcements and reduce duplicate/redundant questions on github issues, slack, twitter, mailing list, etc 
  - I'm thinking of the number of times people asked status of .NET Core project support in VS 2017 or type provider support in .NET Core just a couple of days after release notes/announcements were posted that communicated status. I think this is important because due to the repetition, not every response to these questions was able to sustain the same high level of quality, but if more people are informed through official announcements and such, there is less need for ad-hoc responses.
- Have a reliable way of reaching out to F# users to communicate/orchestrate significant deprecations or gauge usage of techniques or features in question
  - I get the impression that many times interesting changes have caused a lot of hand wringing or are simply passed over because there is concern regarding impact. Obviously no communication network is perfect and some changes will be disruptive regardless of communication, but the devs of the main F# distribution could be more empowered to make critical decisions if they have a way to communicate with their customers.
- Reach out to F# OSS authors in a more concerted and structured effort to ask about their needs and priorities in higher level or overall terms
  - Rather than simply going from github issue to github issue, it might be beneficial to allow authors to explicit communicate major themes, such as:
    - Is the speed and behavior of FCS adequate to deliver usable and reliable editing services on various products? Does it require too much work or workaround to make certain scenarios sustainable or stable?
    - Is the versioning and/or packaging of FSharp.Core adequate to power scenarios that seek to reduce friction of acquisition or usage? Does it require too much work or workarounds to make certain scenarios sustainable or stable?

**Comment by jackfoxy** [comment] 2017-09-05 22:14
@lambdakris you expressed much better than I the kind of things that will appeal to the people who use F#, and make the site more useful for them.

Especially increasing the visibility of release notes. 

Also if the most recent of @cartermp roadmaps was easy to find, and maybe one or 2 roadmaps for high profile OSS projects (FAKE, Paket, Ionide, to name a few). Or perhaps have a section where OSS authors could post roadmaps and high profile "help wanted" bugs.

**Comment by dsyme** [comment] 2017-09-05 22:35
@jackfoxy @lambdakris I sympathise, and of course we want to mobilise people in RFCs and give users a void. 

However I personally think most of those responsibilities listed above lie off the core design of fsharp.org - and instead perhaps in the Core Engineering "Group" zone (note: it's not really a "group"), see http://fsharp.github.io.  There has been talk of reconstituting that "group" as a core-engineering-mobilization-effort along the lines you suggest.

http://fsharp.org is the community's primary chance to interact with people thinking of adopting F# and people looking to install it, and that's unique opportunity

**Comment by Krzysztof-Cieslak** [comment] 2017-09-06 07:59
What those "high profile" OSS projects have to do with Foundation?

**Comment by dsyme** [comment] 2017-09-06 12:29
> What those "high profile" OSS projects have to do with Foundation?

@Krzysztof-Cieslak Nearly all F# OSS projects are entirely independent of the foundation.  

However it seems is reasonable for the FSSF to encourage participation in high profile OSS projects. For example, by linking to them appropriately on http://fsharp.org/use/windows, http://fsharp.org/use/linux etc.  Or by giving links for how to get involved.  Or by mentoring people. At least that's my personal opinion.

**Comment by eromanowski** [comment] 2017-09-30 07:06
**What specific audiences should fsharp.org target?**

This is a moving target based on adoption. Right now, I see targeting the green F# programmer most valuable. This is a brand new strange world with a steep learning curve, getting people comfortable with this paradigm shift will improve adoption rates.

**For each audience, what should be the main goals when a user first visits fsharp.org?**

Give real world examples of the power of F# beyond just the technical capabilities. An animation that shows how checking in code that compiles but has runtime errors and how much of a ripple effect that has throughout the organization, while showcasing how F# solves those problems could be a way to connect to people unfamiliar with F#.

**What major scenarios do we need to support for fsharp.org?**

I can tell what scenarios you shouldn't support. Games, emulators, or anything that requires shared state.

**Comment by 0xaryan** [comment] 2019-04-21 10:40
This issue created over a year ago. Have the redesign process started? If yes, is it open to see the changes? What is the status of this?

**Comment by 0xaryan** [comment] 2019-05-02 15:41
If the design process is still open for changes, it might be a good idea to look at what others done, what UX elements they have and see if it is a good idea for F# website to have those elements too.

**Scala Website**
![an image of scala's website](https://user-images.githubusercontent.com/9091958/57082511-1c19d180-6d0c-11e9-916f-1a1ef9aa4bc7.png)

- A picture of Switzerland in the background, with some history about Scala. [History](https://fsharp.org/history/) is always attractive.
- A straightforward main page that shows the language's logo, download button and API docs with a beautiful design.
- Popup at the top that shows latest blog (Just like [.NET website](https://dot.net)).
- A section that shows where it runs on.
- A section for what features the language has (type inference, pattern matching, etc). Clicking on each features shows a sample example code with descriptions.
- A section for IDEs and Editors that support the language
- An online REPL for interactively running code in the browser
- Courses, trainings, events, blog posts, latest tweets
- Who maintains the language and sponsers

**Haskell Website**
![an image of haskell's website](https://user-images.githubusercontent.com/9091958/57085417-63569100-6d11-11e9-9da0-a290fc331799.png)

- Haskell's Logo at the top
- A lightweight menu with Download, Community and Documentations items
- A simple 3 lines of code showing how to calculate prime numbers in haskell
- An interactive training-oriented REPL that can run code, and guide user how to write play with haskell
- Latest Videos
- A section for what features the language has (type inference, pattern matching, laziness, etc). Clicking on each features shows a sample example code with descriptions.
- Sponsers section
- Wiki section

**F# Website in dot.net**
![an image of F#'s website in dot.net](https://user-images.githubusercontent.com/9091958/57085765-217a1a80-6d12-11e9-8a4e-7054020b5ac0.png)

- F# name with an informative description about the language, with a big button saying "Getting Started"
- A section for what features the language has (type inference, pattern matching, etc). Clicking on each features shows a sample code (no descriptions).
- Beautiful illustrations that can be observed all over the .NET website, introducing F# paradigms, tools and community

**OCaml Website**
![an image of ocaml's website](https://user-images.githubusercontent.com/9091958/57086042-a82ef780-6d12-11e9-89b2-e754f7a51db1.png)

- Search box in the menu
- Big green "Install button" on top of the page, with a Camel in desert background!
- A link to TryOCaml (browser REPL)
- Sample OCaml code, showing how you can express a Tree in the language, cheking if the leaf exist or if the tree has even leaf
- Four big buttons to link user to Learn, Documentation, Packages and Community pages

**Elm Website**
![an image of elm's website](https://user-images.githubusercontent.com/9091958/57086479-6eaabc00-6d13-11e9-8519-b3a9f65f9f5a.png)

- Very simple top banner, with solid blue background, the language's name and description and an install button.
- Languages features section, including performance and JS interop.
- Some real world web apps with screenshots
- Featured users section

**Current F# website**
![an image of F# website](https://user-images.githubusercontent.com/9091958/57086675-d3661680-6d13-11e9-960b-794a46a940a8.png)

- Rich menu with a lot of sub-menus navigating user to other pages of the website
- F# logo and descriptions with a big dropdown "Use F#" button.
- Simple Getting started, Testimonials and news sections
- Sponsered members section

**Idris website**
![an image of Idris's website](https://user-images.githubusercontent.com/9091958/57086972-61420180-6d14-11e9-99c9-2023da728231.png)

- Simpe WP template.
- Language features section, link to documentations and communities as a blog post.

**Kotlin website**
![image](https://user-images.githubusercontent.com/9091958/57087282-f218dd00-6d14-11e9-9745-24ffc4eceae9.png)

- Search feature in the menu
- Big banner showing Conf and other news
- A section for what type of apps this language is used for
- Why Kotlin? section
- Online REPL in the website with 3 examples, and a link to playground with more examples
- IDE and Editors that support the language
- Highlights and social media section

**Swift website**
![image](https://user-images.githubusercontent.com/9091958/57087583-99960f80-6d15-11e9-9c9c-c2c6eb2ec796.png)

- Bare, with a menu.

**Others**
Other website like Elexir, Clojure or Fstar-lang (F*) has the same features with different orders and designs, you might want to take a look.

**Comment by dsyme** [comment] 2021-09-06 18:49
Closing this old discussion

**Closed by dsyme** 2021-09-06 18:49 UTC
Labels: discussion
