### ISSUE TITLE
UX is lacking

### ISSUE THREAD

**Issue by drcrook1** [fsharp/fsfoundation#409] opened 2015-03-06 20:23 UTC
A huge benefit would be a more thought out user experience.  Menus on the left, content in the main region on the right at a minimum.

MSDN does this part well.  JQuery's documentation page is fairly good as well.

The current set up is single page that is a forever long.  Creating the pages in make sense hierarchical views, where a single page is no longer than 2 page lengths would be ideal.

Consolidating information into groups of interest would also be beneficial.  The home page is nice, but the subpages need help.  Not sure if that is an issue with the template being used.

**Comment by dsyme** [comment] 2015-07-31 13:43
@TahaHachana do you see particular ways to action this UX feedback for the site? thx

**Comment by TahaHachana** [comment] 2015-08-02 18:11
There is room for improvement in several areas but I think that they should be planned for the next redesign. I expected the foundation to take over the website and plan the move to a dynamic one while keeping it easy for the community to contribute content.

The bounce rate is high, enabling Webmaster Tools within Google Analytics might help understand the reason.

We also need a call to action on the home page that invites visitors to join the FSSF.

**Comment by voronoipotato** [comment] 2019-06-10 14:52
@ReedCopsey 
Requesting Close, Potential duplicate of https://github.com/fsharp/fsfoundation/issues/680

**Closed** 2019-06-10 19:04 UTC
